---
framework: mocha
tier: small

postMerge:
  pattern: 
    - "./test/**/*.spec.ts""
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
parallelism : 2
version: 1.0.1

